"""empty message

Revision ID: ff0f5d87cb2f
Revises: e34b0a9c6e74
Create Date: 2022-08-11 12:03:41.628932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff0f5d87cb2f'
down_revision = 'e34b0a9c6e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
